### ISSUE TITLE
centos-8-minimal install problem 

### ISSUE THREAD

**Issue by ericdoomed** [uboreas/centos-8-minimal#2]
![bootstrap](https://user-images.githubusercontent.com/33094678/70862402-e5c95380-1f76-11ea-871e-4403845491d5.png)

![centos8](https://user-images.githubusercontent.com/33094678/70862256-e2cd6380-1f74-11ea-8506-6d9bfeb138d3.PNG)
After I got the ccentos-8-minimal.iso, I created a virtual machine and start installing.
Probelm occurs at installing time **"Problems in request:        missing packages :kexec-tools, authselect, grub2, xfsprogs, grub2-tools, e2fsprogs, chrony, lvm2, "**,and whether I choose to continue or not, the installing process will exit.

**Comment by uboreas** [comment]
It seems script got error on line 472 while resolving dependencies. There is temporary file called ".rslv" which holds such dependency problems, can you please check what it looks like?

**Comment by ericdoomed** [comment]
Thanks for answering! Maybe because I wrote too many packages in packages.txt. ![image](https://user-images.githubusercontent.com/33094678/71481598-7e928580-2839-11ea-98bc-c4fc9bc52d3e.png)

**Comment by uboreas** [comment]
Please be sure that there is no white-spaces in front of the hash-mark if the package is disabled.
