### ISSUE TITLE
"Dracut-initqueue timeout" occurs on CentOS8.1 1911

### ISSUE THREAD

**Issue by yukiafronia** [uboreas/centos-8-minimal#3]
"Dracut-initqueue timeout" occurs when running a script to create minimal iso on CentOS8.1 1911.

Will there be any script updates?

Thank you.

**Comment by usbport11** [comment]
Good day!
Main problem: grub.cfg hd:LABEL=CentOS-8-1-1911-x86_64-dvd
Need to change in script bootstap.sh.
```
mkisofs \
      -input-charset utf-8 \
      -o "${pw}/${out}" \
      -b isolinux/isolinux.bin \
      -c isolinux/boot.cat \
      -no-emul-boot \
      -V 'CentOS-8-1-1911-x86_64-dvd' \
      -boot-load-size 4 \
      -boot-info-table \
      -eltorito-alt-boot \
      -e images/efiboot.img \
      -no-emul-boot \
      -R -J -v -T . 2>&1 | cmdot
      cmcheck
```
Upload as txt file.
[bootstrap.txt](https://github.com/uboreas/centos-8-minimal/files/4147516/bootstrap.txt)

**Comment by yukiafronia** [comment]
Thank you!!
