### ISSUE TITLE
minimal iso for centos 8.1

### ISSUE THREAD

**Issue by udayakmr87** [uboreas/centos-8-minimal#4]
Am trying to create minimal ISO for centos 8.1 and getting below output.

<img width="733" alt="pic1" src="https://user-images.githubusercontent.com/42075405/75376004-47058f80-58f5-11ea-9721-b690a52070ba.PNG">

when i trying to boot with the minimal iso getting below error. please suggest.

<img width="507" alt="pic2" src="https://user-images.githubusercontent.com/42075405/75376124-8338f000-58f5-11ea-9bdd-efd563701e9b.PNG">

**Comment by udayakmr87** [comment]
i just want minimal iso without any extra packages.

**Comment by CkNoSFeRaTU** [comment]
That's because it cannot find stage2 as it was changed to CentOS-8-1-1911-x86_64-dvd in 8.1 isos. You can check it by yourself comparing output from **blkid** and **cat /proc/cmdline**
I created PR #6 which adds support for 8.1

**Comment by uboreas** [comment]
Yes, that's right. Project is updated, please pull and try again. Thanks for your feedback!.
