### ISSUE TITLE
My VPS providers CentOS8-x64 ISO is buggy and does not fix it, can I create a ISO by your app here and transfer the created image to the VPS then install from scratch a CentOS8-minimal manually?

### ISSUE THREAD

**Issue by moonprogrammer** [uboreas/centos-8-minimal#5]
Hiya,

My VPS providers CentOS8-x64 ISO is buggy and does not fix it, can I create an ISO by your app here and transfer the created image to the VPS then install from scratch a CentOS8-minimal manually?

Thanks

**Comment by uboreas** [comment]
Hello,
The project is for creating an ISO based on an official release with different package sets to install it in offline environments, nothing else. I am not sure if it fit your requirements. It may worth to give a try.
Thanks.
