### ISSUE TITLE
I'm getting sed errors while running.

### ISSUE THREAD

**Issue by koshrf** [uboreas/centos-8-minimal#7]
I'm using this ISO: CentOS-8.1.1911-x86_64-boot.iso

sudo ./bootstrap.sh run
 ~ mount ISO 
   mount: /vagrant_data/centos-8-minimal/mtemp: WARNING: device write-protected, mounted read-only.
   /vagrant_data/centos-8-minimal/mtemp mounted
 ~ Preparing image template ....sed: -e expression #1, char 68: Invalid range end
sed: -e expression #1, char 58: Invalid range end
sed: -e expression #1, char 68: Invalid range end
sed: -e expression #1, char 58: Invalid range end
sed: -e expression #1, char 68: Invalid range end

**Comment by uboreas** [comment]
Thanks you for your feedback. Since output ISO created based on  official ISO, it doesn't make sense to change it's volume label. I removed such code and keep using the volume label as on official image. Project is updated, please check and let us know if there is still issue. 
Gokhan.

**Comment by uboreas** [comment]
Closed due to inactivity.
