### ISSUE TITLE
Adding packages from external source

### ISSUE THREAD

**Issue by crossbuilder** [uboreas/centos-8-minimal#9]
Hello,

I want to add packages from external source.
Adding "https://my.server.org/rpm/my-package.x86_64.rpm" to packages.txt doesn't work.
While "yumdownloader https://my.server.org/rpm/my-package.x86_64.rpm" pulls the rpm, "yumdownloader --urls https://my.server.org/rpm/my-package.x86_64.rpm" does _not_ print the URL.

Any ideas how to resolve this?

**Comment by uboreas** [comment]
Please add your repository first and then just use the package name like "my-package". Dependency check for every package should be done, so this would be the best way to use external packages through their repo. For example, just like adding pacakges using epel repository.

**Comment by crossbuilder** [comment]
Thanks for the info.

I just hoped, I could skip the createrepo stuff for my single self made rpm ..
